dataset:
  data_dir: 'C:\Users\nicol\OneDrive\Desktop\semester_thesis\Project\data'
  # Linux: '/home/fit_member/Documents/NS_SemesterWork/Project/data/final'
  # Windows: 'G://semester_thesis//Project//data//final'
  batch_size: 2
  num_workers: 0

training:
  k_folds: 5
  epochs: 1
  lr: 0.1